services:
  - type: web
    name: video-classification-app
    env: python
    buildCommand: pip install -r custom_video_classifier/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT custom_video_classifier.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: PORT
        value: 5000
